sudo: required
services:
    - docker

script:
    - docker build -t 175152/nodedockertravistuto . #invalid reference format: repository name must be lowercase
    - docker images 175152/nodeDockerTravisTuto #par contre pour l'image apparament balec

before_deploy:
    - docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD

deploy:
    provider: script
    script: docker push DOCKER_USERNAME/nodedockertravistuto
    on:
        branch: master