sudo: required
services:
    - docker

script:
    - docker build -t 175152/nodedockertravistuto . #invalid reference format: repository name must be lowercase
    - docker images 175152/nodeDockerTravisTuto